Contact Form
Codeinwp/gutenberg-blocks pull request #758
Opened 2021-08-05 10:07 UTC by Soare-Robert-Daniel

## Visual

TODO

## Saving the data

TODO

2021-08-06 20:47 UTC, HardeepAsrani commented
@Soare-Robert-Daniel We won't be saving any data and the email should go to the user's email. By default, it should be the website email but we should give them an option to send it to a different email.

Also we don't really need to give a lot of CSS options, just some good default styles and leave rest to the theme.

2021-08-07 14:34 UTC, selul commented
@HardeepAsrani your plan looks good for me. 
Captcha can be included in this version too, as a separate field.

2021-08-10 05:57 UTC, Soare-Robert-Daniel commented
Test GH CLI﻿

2021-08-16 20:59 UTC, HardeepAsrani commented
Hey @Soare-Robert-Daniel,

I made few changes here:

- Removed extra attributes from the Form block, like templateType and URL as those aren't needed. Templates type shouldn't be decided with an attribute but using Block Variation with a picker like https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-variation-picker
- Input block now has 3-4 different types. Removed Checkbox as it will need a block of its own (we can skip it for this version), and extracted Textarea into a new block as it has a different structure than rest of input fields. Also removed password type as contact forms aren't the place for passwords.
- Variation can be registered from the index.js file straight, plugins aren't needed for it.

Let me know your thoughts. And you can continue your work with the block.

2021-08-17 21:03 UTC, HardeepAsrani commented
@Soare-Robert-Daniel You should use AJAX for this intead of REST.

2021-08-19 20:18 UTC, HardeepAsrani commented
Also, make sure always to include the page link that was used to send the email. As if the form is in "about page" of the website, it should also include the link to that page so it's easier for user to know which page is it coming from.

Also, "subject" attribute name should be good enough, what is email title? 😜

2021-08-24 19:07 UTC, HardeepAsrani requested changes
I've added some line comments that you can go through.

Well done. We should also add form variation for "Contact form" and "Request a quote." We can have a newsletter in the next version as I'd like to explore some newsletter plugins. Make sure you use the __experimentalBlockVariationPicker  for the Placeholder.

2021-08-24 19:07 UTC, HardeepAsrani commented on inc/class-main.php
> +		add_action( 'wp_ajax_get_otter_form', 'get_otter_form' );
Please remove this.

2021-08-24 19:07 UTC, HardeepAsrani commented on inc/class-main.php
> +				array( 'wp-i18n', 'wp-dom-ready', 'jquery', 'wp-api' ),
If possible, can we get rid of jQuery?

2021-08-24 19:07 UTC, HardeepAsrani commented on inc/plugins/class-options-settings.php
> +				'sanitize_callback' => '' /* function( $array ) {
This needs to be added.

2021-08-24 19:07 UTC, HardeepAsrani commented on inc/server/class-form-server.php
> +		register_rest_route(
Why do we have a method for GET?

2021-08-24 19:07 UTC, HardeepAsrani commented on inc/server/class-form-server.php
> +		$email_subject = '[Otter] ' . ( isset( $data['emailSubject'] ) ? $data['emailSubject'] : __( 'A new submission', 'otter-blocks' ) );
Default subject can be "A new form submission on (website name)," also remove "[Otter]" prefix.

2021-08-24 19:07 UTC, HardeepAsrani commented on inc/server/class-form-server.php
> +		$headers = array( 'Content-Type: text/html; charset=UTF-8', 'From: Admin <' . $from . '>' );
From website name or something better, Admin doesn't look good in email.

2021-08-24 19:07 UTC, HardeepAsrani commented on inc/server/class-form-server.php
> +	private function prepare_body( $data ) {
We should include the page link in the body, a link like:

Form submission from: https://example.com/contact

2021-08-25 06:13 UTC, Soare-Robert-Daniel commented on inc/server/class-form-server.php
> +		register_rest_route(
It was for testing

2021-08-25 06:14 UTC, Soare-Robert-Daniel commented on inc/class-main.php
> +				array( 'wp-i18n', 'wp-dom-ready', 'jquery', 'wp-api' ),
yes

2021-08-30 09:44 UTC, Soare-Robert-Daniel commented
@irinelenache we need a test on this PR

This block will require a special setup since it needs to send emails.

To add the email functionality, add the following plugin: https://wordpress.org/plugins/wp-mail-smtp/

They support multiple providers (and have tutorials on them when you set up one ); I recommend the GMAIL since it is the one I tested.

The block support to send the email to another address. You can use 10minute mail or our emails from slack.

2021-09-02 10:15 UTC, irinelenache commented
@Soare-Robert-Daniel Nice work 🚀  Tested it and found a few issues:

- [ ] The form input boxes look different in editor and frontend
editor: https://vertis.d.pr/rZvOhv
frontend: https://vertis.d.pr/hh2c6D

- [ ] The input box border has different colors https://vertis.d.pr/3UpGrg
- [ ] After hitting submit button, i get this error in console https://vertis.d.pr/qUs5t5 (after about 5 seconds)
- [ ] The **Success** message is not that visible, makes it hard to know that the form was submitted. https://vertis.d.pr/ezmIAC
- [ ] The **message input** font is different than for other inputs https://vertis.d.pr/eVzGnU
- [ ] The email subject is always _**A new form submission on..**_ , even if i change it to something else in form settings

2021-09-02 11:10 UTC, Soare-Robert-Daniel commented
@irinelenache, the style difference depends on the theme and not the block; all we do is the layout. The other depends on the theme and browser.

2021-09-02 12:08 UTC, Soare-Robert-Daniel commented
@irinelenache made an update for the email subject problem

2021-09-05 21:31 UTC, HardeepAsrani commented
@irinelenache Let us know when you're done with this.

2021-09-05 21:32 UTC, HardeepAsrani commented
@Soare-Robert-Daniel Remember to put the issue in QA column so QA team can easily track it.

2021-09-07 08:17 UTC, irinelenache commented
@Soare-Robert-Daniel Tested again and some issues are still present:

> The message input font is different than for other inputs https://vertis.d.pr/eVzGnU
> The input box border has different colors https://vertis.d.pr/3UpGrg

If it's ok to let them like this, we can move this to **Ready to merge** 👍

2021-09-07 16:33 UTC, merged